service:
  group: SosMedico
  name: api-gateway
  version: 0.1.0
gateway:
  endpoint:
    schema: http
    path: /sosm-api/
    port: 9000
  admin:
    schema: http
    path: /sosm-api-admin
    port: 9001
    scurity:
      enabled: true
      jwt:
        secret: R7mT6PaYxC1cfnaDvT51jLWP7fcLaOoMmkxoaaTgZUo7GFv8lcbzm7LJzytHggAU
        expiration:
          enabled: true
          minutes: 13149000
  cors:
    origin:
        - "*"
    methods:
        - GET
        - PUT
        - POST
        - DELETE
    headers:
        - Accept
        - Authorization
        - Content-Type
        - X-CSRF-Token
api:
  name: SosMedicoAPI
  endpoints:
  - name: uaa
    path: /uaa-service
    version: 1
    proxy:
      targets:
      - schema: http
        host: localhost:7777
        path: /api/v1
      - schema: http
        host: localhost:7778
        path: /api/v1
      balancing: # one from "round-robin" or "random"
        strategy: random
  - name: account
    path: /account-service
    version: 1
    proxy:
      targets:
      - schema: http
        host: localhost:8888
        path: /api/v1
      - schema: http
        host: localhost:8889
        path: /api/v1
      balancing: # one from "round-robin" or "random"
        strategy: random