service:
  group: SosMedico
  name: api-gateway
  version: 0.1.0
gateway:
  endpoint:
    schema: http
    path: "/sosm-api"
    port: '9000'
  admin:
    schema: http
    path: "/sosm-api-admin"
    port: '9001'
    scurity:
      enabled: true
      jwt:
        secret: R7mT6PaYxC1cfnaDvT51jLWP7fcLaOoMmkxoaaTgZUo7GFv8lcbzm7LJzytHggAU
        expiration:
          enabled: true
          minutes: 13149000
  cors:
    origin:
        - *
    methods:
        - GET
        - PUT
        - POST
        - DELETE
    headers:
        - Accept
        - Authorization
        - Content-Type
        - X-CSRF-Token