service:
  group: SosMedico
  name: api-gateway
  version: 0.1.0
log:
  path: logs
  filename: gateway.log
  console: true
  level: debug
  json: false
  maxSize: 5
  maxAge: 60
  maxBackups: 90
  compress: true
  caller: false
gateway:
  endpoint:
    schema: http
    path: /sosm-api/
    port: 9000
  admin:
    schema: http
    path: /sosm-api-admin
    port: 9001
    scurity:
      enabled: true
      jwt:
        secret: R7mT6PaYxC1cfnaDvT51jLWP7fcLaOoMmkxoaaTgZUo7GFv8lcbzm7LJzytHggAU
        expiration:
          enabled: true
          minutes: 13149000
  cors:
    origin:
        - "*"
    methods:
        - GET
        - PUT
        - POST
        - DELETE
    headers:
        - Accept
        - Authorization
        - Content-Type
        - X-CSRF-Token
api:
  name: SosMedicoAPI
  endpoints:
  - name: uaa
    path: /uaa-service
    version: 1
    proxy:
      path: /api/v1
      schema: http
      targets:
      - localhost:7777
      - localhost:7778
      balancing: # one from "round-robin" or "random"
        strategy: round-robin
  - name: account
    path: /account-service
    version: 1
    proxy:
      path: /api/v2
      schema: http
      targets:
      - localhost:7777
      - localhost:7778
      balancing: # one from "round-robin" or "random"
        strategy: random

